<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="57099" started-at="2017-12-04T16:17:59Z" finished-at="2017-12-04T16:18:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="57099" started-at="2017-12-04T16:17:59Z" finished-at="2017-12-04T16:18:57Z">
      <class name="ddfPack.tests.LoginTest">
        <test-method status="PASS" signature="init()[pri:0, instance:ddfPack.tests.LoginTest@1fc6dc4]" name="init" is-config="true" duration-ms="13" started-at="2017-12-04T21:47:59Z" finished-at="2017-12-04T21:47:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="doLoginTest(java.util.HashMap)[pri:0, instance:ddfPack.tests.LoginTest@1fc6dc4]" name="doLoginTest" duration-ms="55163" started-at="2017-12-04T21:48:00Z" data-provider="getData" finished-at="2017-12-04T21:48:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y, ExpectedResult=Success, Username=seleniumtraining11292017@gmail.com, Browser=Firefox, Password=SeleniumTester$}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to locate element: {"method":"css selector","selector":"[class^='xzicon-apps-crm']"}
Command duration or timeout: 34.11 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'OSIT-L-0463', ip: '10.0.0.6', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 08eb190c-4bc6-4046-a24a-aaae7c9031d8
*** Element info: {Using=css selector, value=[class^='xzicon-apps-crm']}]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to locate element: {"method":"css selector","selector":"[class^='xzicon-apps-crm']"}
Command duration or timeout: 34.11 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'OSIT-L-0463', ip: '10.0.0.6', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 08eb190c-4bc6-4046-a24a-aaae7c9031d8
*** Element info: {Using=css selector, value=[class^='xzicon-apps-crm']}
	at org.testng.Assert.fail(Assert.java:94)
	at ddfPack.base.BaseTest.reportFail(BaseTest.java:206)
	at ddfPack.base.BaseTest.getElement(BaseTest.java:165)
	at ddfPack.base.BaseTest.isElementPresent(BaseTest.java:186)
	at ddfPack.base.BaseTest.doLogin(BaseTest.java:107)
	at ddfPack.tests.LoginTest.doLoginTest(LoginTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="testClosure()[pri:0, instance:ddfPack.tests.LoginTest@1fc6dc4]" name="testClosure" is-config="true" duration-ms="1022" started-at="2017-12-04T21:48:55Z" finished-at="2017-12-04T21:48:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClosure -->
        <test-method status="SKIP" signature="doLoginTest(java.util.HashMap)[pri:0, instance:ddfPack.tests.LoginTest@1fc6dc4]" name="doLoginTest" duration-ms="3" started-at="2017-12-04T21:48:57Z" data-provider="getData" finished-at="2017-12-04T21:48:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, ExpectedResult=Success, Username=seleniumtraining11292017@gmail.com, Browser=Chrome, Password=SeleniumTester$}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test as the run mode is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test as the run mode is set to N
	at ddfPack.tests.LoginTest.doLoginTest(LoginTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="testClosure()[pri:0, instance:ddfPack.tests.LoginTest@1fc6dc4]" name="testClosure" is-config="true" duration-ms="44" started-at="2017-12-04T21:48:57Z" finished-at="2017-12-04T21:48:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClosure -->
      </class> <!-- ddfPack.tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
